{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
{{- include "default.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx-internal
{{- include "default.annotations" . | indent 4 }}
spec:
  rules:
  - host: {{ .Values.ingress.domainName }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: 80
{{- end }}
