apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
{{- include "default.labels" . | indent 4 }}
  annotations:
{{- include "default.annotations" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
{{- include "default.labels" . | indent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
