apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-env"
  labels:
{{- include "default.labels" . | indent 4 }}
  annotations:
{{- include "default.annotations" . | indent 4 }}
data:
{{ toYaml .Values.envConfig | indent 2 }}
