# harness.io/skip-file-for-deploy

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service_name }}
  labels:
{{- include "default.labels" . | indent 4 }}
  annotations:
{{- include "default.annotations" . | indent 4 }}
